### ISSUE TITLE
Adding new git repo with older commit

### ISSUE THREAD

**Issue by ClovDev** [CybercentreCanada/assemblyline-service-yara#1] opened 2020-07-10 15:52 UTC
Hi,

With playing with the yara module I wanted to add some other yara rules. For example https://github.com/reversinglabs/reversinglabs-yara-rules would be really nice to add. The problems is that I got a the message: "There are no new commits, skipping repository...". With seems to be due the "previous_update" var being a single global variabel. If one source is updated it leads to newly added ones to have problems getting their initial parse. This goes wrong in yara_updater.py line 166.

Im willing to help out with coding, just would like to know what would be the best direction to solve this.

**Comment by hkozushk** [comment] 2020-09-01 13:02
I am curious on how you added it, please fill in the gaps below:

https://github.com/reversinglabs/reversinglabs-yara-rules.git
output filename: yara
match pattern: ?

**Comment by ClovDev** [comment] 2020-09-01 13:28
I used the pattern: ^.*.yara$

In the mean while was using this to bypass the problem:
`$ docker exec -it assemblyline4_beta_4_redis_1 /bin/bash`

`$ redis-cli HGET service-updates YARA "{"next_update": "2020-07-27T15:35:57.671103Z", "previous_update": "2020-07-26T15:35:56.671039Z" ..."`

Change the previous update string to something before the last commit of the repo
`
$ redis-cli HSET service-updates YARA "{"next_update": "2020-07-27T15:35:57.671103Z", "previous_update": "2020-02-26T15:35:56.671039Z" ..."`

This way I can add any repo without problems, just some extra work.

**Comment by hkozushk** [comment] 2020-09-01 13:40
Thank you very much for the quick response :-)

**Comment by cccs-jp** [comment] 2020-10-17 14:37
@ClovDev are you able to make a PR? Otherwise we can look into fixing this ourselves. Let us know, thanks!

**Comment by ClovDev** [comment] 2020-10-29 09:01
Hi,

Sorry missed you reply, I was under the assumption this was fixed in a newer version. In the google mailing list it was mentioned that a fix already was present and was te be released in the next version/beta.

It was one of the latest replies in the "Assemblyline 4 - Beta 4 is out!" mail chain:
"Yes that was definitely a problem. It was fixed on a dev branch but we haven't pushed new beta builds for the core framework. From now on, any signature change or signature source change will trigger an auto-update within a 5 min window. I can look into pushing new builds soon."

**Comment by cccs-jp** [comment] 2020-10-29 13:22
Hi @ClovDev, we've made many improvement to the service recently, @cccs-rs do you know if this was part of our fixes?

**Comment by cccs-rs** [comment] 2020-10-29 13:57
@ClovDev  if I understand the problem correctly, the problem is:

Suppose today it updates and there's a 24h interval for each update:
It updates all the sources so previous_update=today, next_update=tomorrow

If you want to add a source whose last commit was in 2012, the updater doesn't pick up on it because "it's too old" relative to today in 2020.

So previous/next_update is acting a global setting where this should be based on each source individually, is that correct?

**Comment by ClovDev** [comment] 2020-10-29 15:58
That is a perfect summary of the problem.

**Comment by cccs-jp** [comment] 2020-10-29 16:31
@ClovDev fix is in code review, cheers

**Comment by cccs-rs** [comment] 2020-10-29 16:54
This may take some time to investigate to see if I can come up with a clever fix.

Because you could always force last_update to be None and it would avoid that check but I can imagine there would be adverse effects for something like to other sources.

**Comment by cccs-rs** [comment] 2020-10-30 11:18
@ClovDev, what you've heard from the mail chain is correct!

This issue has been patched in the UI component where if you add/modify the source list, the previous_update and next_update fields are cleared so it forces the updater to grab all sources the next time it runs.

@cccs-jp, this patch applies to all services using sources.

**Comment by ClovDev** [comment] 2020-10-30 12:19
That also works for me. Any idea when there will be a new beta or v1 launch, so that is becomes available?

**Comment by cccs-rs** [comment] 2020-10-30 12:28
You can check out our updated [assemblyline4_docs](https://cybercentrecanada.github.io/assemblyline4_docs/).

From what I've seen in the docs, these are using the stable tags (I think before they were beta) and so the patch should be available for use (as well as other goodies 😉)!

**Comment by ClovDev** [comment] 2020-10-30 12:53
Cool, didnt't know that happened 🥰 , will look into the updating or get a new instance up and running. Lets close this, if something is not working I'll create an issue at the ui component.

**Closed** 2020-10-30 13:07 UTC
